#!/bin/sh -eu

run() {
	while [ "$#" -gt 0 ]; do
		printf "%s:\n" "$1" >> "$o"
		valgrind --leak-check=full \
			--show-leak-kinds=all \
			--track-origins=yes \
			--verbose \
			kakeidoscope "$2" 1 >> "$o" > /dev/null 2>> "$o"
		[ "$#" -ne 2 ] && printf "\n" >> "$o"
		shift 2
	done
}

main() {
	o="mem.out" && : > "$o"
	. mktests
}

main "$@"
