#!/usr/bin/env sh
set -eu

run()
{
	while [ "$#" -gt 0 ]; do
		printf "%s:\n" "$1" >> "$o"
		> /dev/null 2>> "$o" time kakeidoscope "$2" 1
		if [ "$#" -ne 2 ]; then printf "\n" >> "$o"; fi
		shift 2
	done
}

o="runtime.out"; : > "$o"
. mktests
