#!/bin/sh -eu

run() {
	while [ "$#" -gt 0 ]; do
		printf "%s:\n" "$1" >> "$o"
		time kakeidoscope "$2" 1 > /dev/null 2>> "$o"
		[ "$#" -ne 2 ] && printf "\n" >> "$o"
		shift 2
	done
}

main() {
	o="runtime.out" && : > "$o"
	. mktests
}

main "$@"
